# Generated by Django 4.2.3 on 2023-07-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Intermediate", "Intermediate"),
                            ("Advance", "Advance"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default.png", upload_to="Profile Pictures"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("member_since", models.CharField(default="Jul 2023", max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_name", models.CharField(max_length=255)),
                (
                    "language_level",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Conversational", "Conversational"),
                            ("Fluent", "Fluent"),
                            ("Native", "Native"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Associate", "Associate"),
                            ("Certificate", "Certificate"),
                            ("B.A", "B.A"),
                            ("BSC", "BSC"),
                            ("M.A", "M.A"),
                            ("MSC", "MSC"),
                            ("PHD", "PHD"),
                            ("LLB", "LLB"),
                            ("other", "other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("major_subject", models.CharField(max_length=255)),
                ("country_name", models.CharField(max_length=255)),
                ("institute_name", models.CharField(max_length=255)),
                ("year_of_graduation", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate", models.CharField(max_length=255)),
                ("certified_from", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
