# Generated by Django 4.2.3 on 2023-11-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuserprofile",
            name="member_since",
            field=models.CharField(default="Nov 2023", max_length=255),
        ),
    ]
