DELIVERY_DURATION = (
    ("1d", "1 Day Delivery"),
    ("2d", "2 Days Delivery"),
    ("3d", "3 Days Delivery"),
    ("4d", "4 Days Delivery"),
    ("5d", "5 Days Delivery"),
    ("6d", "6 Days Delivery"),
    ("7d", "7 Days Delivery"),
    ("8d", "8 Days Delivery"),
    ("9d", "9 Days Delivery"),
    ("10d", "10 Days Delivery"),
    ("14d", "14 Days Delivery"),
    ("21d", "21 Days Delivery"),
    ("25d", "25 Days Delivery"),
    ("30d", "30 Days Delivery"),
    ("45d", "45 Days Delivery"),
    ("60d", "60 Days Delivery"),
    ("75d", "75 Days Delivery"),
    ("90d", "90 Days Delivery"),

)