# Generated by Django 4.2.3 on 2023-08-04 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 5, 4, 33, 53, 129295)
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 5, 4, 33, 53, 129295)
            ),
        ),
    ]
