# Generated by Django 4.2.3 on 2023-08-04 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_review_created_at_alter_review_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 5, 4, 46, 21, 202419)
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 5, 4, 46, 21, 202419)
            ),
        ),
    ]
