# Generated by Django 4.2.3 on 2023-11-26 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_review_created_at_alter_review_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 25, 18, 10, 15, 371715)
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 25, 18, 10, 15, 371715)
            ),
        ),
    ]
