# Generated by Django 4.2.3 on 2023-08-04 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="I will", max_length=80)),
                ("description", models.TextField(max_length=2999)),
                ("images", models.ImageField(upload_to="gig images")),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="gig videos"),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="gig documents"),
                ),
                ("category", models.CharField(max_length=45)),
                ("sub_category", models.CharField(max_length=45)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "search_tags",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandardPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("description", models.TextField(max_length=125)),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("1d", "1 Day Delivery"),
                            ("2d", "2 Days Delivery"),
                            ("3d", "3 Days Delivery"),
                            ("4d", "4 Days Delivery"),
                            ("5d", "5 Days Delivery"),
                            ("6d", "6 Days Delivery"),
                            ("7d", "7 Days Delivery"),
                            ("8d", "8 Days Delivery"),
                            ("9d", "9 Days Delivery"),
                            ("10d", "10 Days Delivery"),
                            ("14d", "14 Days Delivery"),
                            ("21d", "21 Days Delivery"),
                            ("25d", "25 Days Delivery"),
                            ("30d", "30 Days Delivery"),
                            ("45d", "45 Days Delivery"),
                            ("60d", "60 Days Delivery"),
                            ("75d", "75 Days Delivery"),
                            ("90d", "90 Days Delivery"),
                        ],
                        max_length=3,
                    ),
                ),
                ("pages", models.IntegerField()),
                ("revisions", models.IntegerField()),
                ("content_upload", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gig",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_package",
                        to="gigs.gig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("description", models.TextField(max_length=125)),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("1d", "1 Day Delivery"),
                            ("2d", "2 Days Delivery"),
                            ("3d", "3 Days Delivery"),
                            ("4d", "4 Days Delivery"),
                            ("5d", "5 Days Delivery"),
                            ("6d", "6 Days Delivery"),
                            ("7d", "7 Days Delivery"),
                            ("8d", "8 Days Delivery"),
                            ("9d", "9 Days Delivery"),
                            ("10d", "10 Days Delivery"),
                            ("14d", "14 Days Delivery"),
                            ("21d", "21 Days Delivery"),
                            ("25d", "25 Days Delivery"),
                            ("30d", "30 Days Delivery"),
                            ("45d", "45 Days Delivery"),
                            ("60d", "60 Days Delivery"),
                            ("75d", "75 Days Delivery"),
                            ("90d", "90 Days Delivery"),
                        ],
                        max_length=3,
                    ),
                ),
                ("pages", models.IntegerField()),
                ("revisions", models.IntegerField()),
                ("content_upload", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gig",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_package",
                        to="gigs.gig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasicPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("description", models.TextField(max_length=125)),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("1d", "1 Day Delivery"),
                            ("2d", "2 Days Delivery"),
                            ("3d", "3 Days Delivery"),
                            ("4d", "4 Days Delivery"),
                            ("5d", "5 Days Delivery"),
                            ("6d", "6 Days Delivery"),
                            ("7d", "7 Days Delivery"),
                            ("8d", "8 Days Delivery"),
                            ("9d", "9 Days Delivery"),
                            ("10d", "10 Days Delivery"),
                            ("14d", "14 Days Delivery"),
                            ("21d", "21 Days Delivery"),
                            ("25d", "25 Days Delivery"),
                            ("30d", "30 Days Delivery"),
                            ("45d", "45 Days Delivery"),
                            ("60d", "60 Days Delivery"),
                            ("75d", "75 Days Delivery"),
                            ("90d", "90 Days Delivery"),
                        ],
                        max_length=3,
                    ),
                ),
                ("pages", models.IntegerField()),
                ("revisions", models.IntegerField()),
                ("content_upload", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gig",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basic_package",
                        to="gigs.gig",
                    ),
                ),
            ],
        ),
    ]
