# Generated by Django 4.2.3 on 2023-07-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gigs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicpackage",
            name="gig",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_package",
                to="gigs.gig",
            ),
        ),
        migrations.AlterField(
            model_name="premiumpackage",
            name="gig",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="premium_package",
                to="gigs.gig",
            ),
        ),
        migrations.AlterField(
            model_name="standardpackage",
            name="gig",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_package",
                to="gigs.gig",
            ),
        ),
    ]
