# Generated by Django 4.2.3 on 2023-08-04 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gigs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="total_orders",
        ),
    ]
